### ISSUE TITLE
[frontends] Externalize configurations

### ISSUE THREAD

**Issue by dbgjerez** [dbgjerez/workshop-cdc#11]
When a ReactJS application is built as a production mode with static files. Nginx needs read the backend url from a ENV var. 

https://www.freecodecamp.org/news/how-to-implement-runtime-environment-variables-with-create-react-app-docker-and-nginx-7f9d42a91d70/

**Comment by dbgjerez** [comment]
I've created the branch to test the previous documentation website

**Comment by JuanmaBM** [comment]
This post could be a possible solution: https://www.freecodecamp.org/news/how-to-implement-runtime-environment-variables-with-create-react-app-docker-and-nginx-7f9d42a91d70/

**Comment by JuanmaBM** [comment]
The previous solution can't be applied because the config app file is involved in the API URL build process. 

Try this solution: https://www.npmjs.com/package/react-inject-env 

PD: I tried this package unsuccessfully, but I think a little refactoring is needed to apply

**Comment by dbgjerez** [comment]
https://github.com/facebook/create-react-app/issues/13447

**Comment by dbgjerez** [comment]
I've resolved the issue of creating a new .js script file, which is loaded on start up. OpenShift set the file from a configmap.
