### ISSUE TITLE
[ms-users] Camel route for service rest

### ISSUE THREAD

**Issue by dbgjerez** [dbgjerez/workshop-cdc#17]

**Comment by dbgjerez** [comment]
@ryanezil Subes aquí el código de tu frontal de MongoDB

**Comment by ryanezil** [comment]
@dbgjerez It's uploaded here: https://github.com/dbgjerez/workshop-cdc/tree/feature/mongodb-front/apps/mongodb-front

New branch created: [feature/mongodb-front](https://github.com/dbgjerez/workshop-cdc/tree/feature/mongodb-front)

**Comment by dbgjerez** [comment]
I've adapted the code and merged it
