### ISSUE TITLE
[ReactJS] Backend urls configuration

### ISSUE THREAD

**Issue by dbgjerez** [dbgjerez/workshop-cdc#29]
Backend URLs are in their own config map for each frontend application. This approach makes it not easy to modify the system each time it's deployed, so we should make some changes.  

The change is to create an ArgoCD application with all the configurations, for example, one config map for each application.  An important step is to automatize how this config map is modified with the correct URL.

**Comment by dbgjerez** [comment]
I've found another option:

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}
data:
  config.js: |
    var appConfig = {
      "BACKEND_USERS_URL": {{ (lookup "route.openshift.io/v1" "Route" .Release.Namespace .Values.service.name).spec.host }}
    };

**Comment by dbgjerez** [comment]
I've found another option:

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}
data:
  config.js: |
    var appConfig = {
      "BACKEND_USERS_URL": {{ (lookup "route.openshift.io/v1" "Route" .Release.Namespace .Values.service.name).spec.host }}
    };

**Comment by dbgjerez** [comment]
> ConfigMap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}
data:
  config.js: |
    var appConfig = {
      "BACKEND_USERS_URL": {{ (lookup "route.openshift.io/v1" "Route" .Release.Namespace .Values.backend.name).spec.host | quote }}
    };  
```

> New values.yaml
```
backend:
  name: ms-users-camel
```

**Comment by harimohan1990** [comment]
is it still open

**Comment by dbgjerez** [comment]
Hi, @harimohan1990 I hope to close it tomorrow when I'll test it

**Comment by dbgjerez** [comment]
The solution works fine after a test process
